#!/usr/bin/env bash
#
# setup-dhcp-server.sh
#
# Turns the first wired Ethernet NIC into a DHCP server on a live-USB
# Ubuntu 26.04 desktop.
#
#   - Installs dnsmasq (DHCP/DNS server) and iperf3 via apt
#   - Takes the interface away from NetworkManager (and stops
#     systemd-networkd if it's running) so nothing else fights over it
#   - Sets a static IP of 10.0.0.1/24 on that interface
#   - Runs dnsmasq bound only to that interface, handing out
#     10.0.0.10 - 10.0.0.20 to DHCP clients
#
# Must be run as root (sudo). Designed for a live session: it edits
# live system state, not netplan/persistent config, so a reboot returns
# you to normal.

# AI vibe code 2026-09-25 by Rodney Beede

set -euo pipefail

log()  { echo -e "\e[1;32m[+]\e[0m $*"; }
warn() { echo -e "\e[1;33m[!]\e[0m $*"; }
err()  { echo -e "\e[1;31m[x]\e[0m $*" >&2; }

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root. Try: sudo $0"
    exit 1
fi

STATIC_IP="10.0.0.1"
PREFIX="24"
DHCP_RANGE_START="10.0.0.10"
DHCP_RANGE_END="10.0.0.20"
LEASE_TIME="12h"

### 1. Find the first wired Ethernet interface #############################
# Look at every "ether" link that isn't loopback/virtual/wireless, then
# pick the first one whose driver is a real Ethernet driver (skips
# docker0, virbrX, veth*, wlan*, etc).
log "Detecting wired Ethernet interfaces..."

IFACE=""
for dev in $(ls /sys/class/net/); do
    [[ "$dev" == "lo" ]] && continue
    [[ -d "/sys/class/net/$dev/wireless" ]] && continue          # skip wifi
    [[ -e "/sys/class/net/$dev/device" ]] || continue            # skip virtual (bridges, veth, docker)
    link_type=$(cat "/sys/class/net/$dev/type" 2>/dev/null || echo "")
    [[ "$link_type" == "1" ]] || continue                        # 1 = ARPHRD_ETHER
    IFACE="$dev"
    break
done

if [[ -z "$IFACE" ]]; then
    err "No wired Ethernet interface found. Aborting."
    exit 1
fi

log "Using wired interface: $IFACE"

### 2. Install packages ######################################################
log "Updating apt and installing dnsmasq + iperf3..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y dnsmasq iperf3

### 3. Get NetworkManager / systemd-networkd out of the way #################
if systemctl list-unit-files | grep -q '^NetworkManager\.service'; then
    log "Telling NetworkManager to stop managing $IFACE..."
    if command -v nmcli >/dev/null 2>&1; then
        nmcli device set "$IFACE" managed no || true
    fi
    log "Stopping and disabling NetworkManager entirely..."
    systemctl stop NetworkManager.service || true
    systemctl disable NetworkManager.service || true
fi

if systemctl list-unit-files | grep -q '^systemd-networkd\.service'; then
    if systemctl is-active --quiet systemd-networkd.service; then
        log "Stopping systemd-networkd..."
        systemctl stop systemd-networkd.service || true
        systemctl disable systemd-networkd.service || true
    fi
fi

# dnsmasq ships with its own tiny DNS stub that binds :53 and can clash
# with systemd-resolved. We only need DHCP, so stop it if present.
if systemctl is-active --quiet systemd-resolved.service 2>/dev/null; then
    warn "systemd-resolved is running; leaving it alone (dnsmasq will be DHCP-only, port 53 off)."
fi

### 4. Assign the static IP manually #########################################
log "Flushing existing addresses on $IFACE and setting ${STATIC_IP}/${PREFIX}..."
ip addr flush dev "$IFACE" || true
ip link set "$IFACE" up
ip addr add "${STATIC_IP}/${PREFIX}" dev "$IFACE"

### 5. Configure dnsmasq as a DHCP-only server on this interface ############
DNSMASQ_CONF="/etc/dnsmasq.d/live-dhcp-${IFACE}.conf"
log "Writing dnsmasq config to $DNSMASQ_CONF..."

mkdir -p /etc/dnsmasq.d
cat > "$DNSMASQ_CONF" <<EOF
# Generated by setup-dhcp-server.sh
interface=${IFACE}
bind-interfaces
except-interface=lo
# DHCP only, no DNS resolving duties from this server
port=0
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${LEASE_TIME}
dhcp-option=option:router,${STATIC_IP}
dhcp-authoritative
EOF

# Make sure the base dnsmasq.conf doesn't have a conflicting global
# interface restriction, and that it's including the .d directory.
if ! grep -q '^conf-dir=/etc/dnsmasq.d' /etc/dnsmasq.conf 2>/dev/null; then
    echo 'conf-dir=/etc/dnsmasq.d,*.conf' >> /etc/dnsmasq.conf
fi

log "Restarting dnsmasq..."
systemctl unmask dnsmasq.service || true
systemctl enable dnsmasq.service
systemctl restart dnsmasq.service

### 6. Summary ################################################################
log "Done."
echo
echo "  Interface : $IFACE"
echo "  Static IP : ${STATIC_IP}/${PREFIX}"
echo "  DHCP range: ${DHCP_RANGE_START} - ${DHCP_RANGE_END} (lease ${LEASE_TIME})"
echo
echo "Check leases with:   sudo cat /var/lib/misc/dnsmasq.leases"
echo "Check dnsmasq status: systemctl status dnsmasq"
echo "Run an iperf3 server: iperf3 -s -B ${STATIC_IP}"
